use geo_registry::register_plugin;
use geo_registry::registry::ToolResult;
use geo_registry::PluginRegistry;

pub fn register_tools(registry: &mut PluginRegistry) {
    register_plugin!(registry, "ocean", "Oceanography — currents, bleaching, upwelling, fisheries", PluginCategory::Process, [
        sync "ocean_coral_bleaching" => "Coral bleaching risk from DHW (Degree Heating Weeks)" ; serde_json::json!({"type":"object","properties":{"weekly_sst":{"type":"array","items":{"type":"number"}},"max_monthly_mean":{"type":"number"}},"required":["weekly_sst","max_monthly_mean"]}) => |args| -> ToolResult { let s:Vec<f64>=args["weekly_sst"].as_array().map(|a|a.iter().filter_map(|v|v.as_f64()).collect()).unwrap_or_default();let m=args["max_monthly_mean"].as_f64().unwrap_or(28.0);let p=crate::OceanPlugin::new(Default::default());serde_json::to_value(p.coral_bleaching(&s,m)).map_err(geo_core::GeoError::Serde) },
        sync "ocean_upwelling" => "Ekman upwelling index from wind stress" ; serde_json::json!({"type":"object","properties":{"wind_stress_n_m2":{"type":"number"},"latitude_deg":{"type":"number"}},"required":["wind_stress_n_m2","latitude_deg"]}) => |args| -> ToolResult { let ws=args["wind_stress_n_m2"].as_f64().unwrap_or(0.1);let lat=args["latitude_deg"].as_f64().unwrap_or(30.0);let p=crate::OceanPlugin::new(Default::default());serde_json::to_value(p.upwelling(ws,lat)).map_err(geo_core::GeoError::Serde) },
        sync "ocean_geostrophic" => "Geostrophic current from SSH gradient" ; serde_json::json!({"type":"object","properties":{"dssh_dx":{"type":"number"},"dssh_dy":{"type":"number"},"latitude_deg":{"type":"number"}},"required":["dssh_dx","dssh_dy","latitude_deg"]}) => |args| -> ToolResult { let dx=args["dssh_dx"].as_f64().unwrap_or(0.0);let dy=args["dssh_dy"].as_f64().unwrap_or(0.0);let lat=args["latitude_deg"].as_f64().unwrap_or(30.0);let p=crate::OceanPlugin::new(Default::default());serde_json::to_value(p.geostrophic(dx,dy,lat)).map_err(geo_core::GeoError::Serde) },
        sync "ocean_slr" => "Sea level rise projection" ; serde_json::json!({"type":"object","properties":{"current_rate_mm_yr":{"type":"number"},"acceleration_mm_yr2":{"type":"number"},"base_year":{"type":"integer"}},"required":["current_rate_mm_yr","acceleration_mm_yr2","base_year"]}) => |args| -> ToolResult { let r=args["current_rate_mm_yr"].as_f64().unwrap_or(3.5);let a=args["acceleration_mm_yr2"].as_f64().unwrap_or(0.1);let b=args["base_year"].as_u64().unwrap_or(2020)as u16;let p=crate::OceanPlugin::new(Default::default());serde_json::to_value(p.slr(r,a,b)).map_err(geo_core::GeoError::Serde) },
        sync "ocean_fisheries" => "Fisheries potential from chlorophyll and SST" ; serde_json::json!({"type":"object","properties":{"chlorophyll_mg_m3":{"type":"number"},"sst_c":{"type":"number"},"target_type":{"type":"string","enum":["pelagic","demersal","reef","general"]}},"required":["chlorophyll_mg_m3","sst_c","target_type"]}) => |args| -> ToolResult { let c=args["chlorophyll_mg_m3"].as_f64().unwrap_or(0.5);let s=args["sst_c"].as_f64().unwrap_or(25.0);let t=args["target_type"].as_str().unwrap_or("pelagic");let p=crate::OceanPlugin::new(Default::default());serde_json::to_value(p.fisheries(c,s,t)).map_err(geo_core::GeoError::Serde) },
        sync "ocean_acidification" => "Aragonite saturation state" ; serde_json::json!({"type":"object","properties":{"ph":{"type":"number"},"sst_c":{"type":"number"}},"required":["ph","sst_c"]}) => |args| -> ToolResult { let ph=args["ph"].as_f64().unwrap_or(8.1);let s=args["sst_c"].as_f64().unwrap_or(25.0);let p=crate::OceanPlugin::new(Default::default());serde_json::to_value(p.acidification(ph,s)).map_err(geo_core::GeoError::Serde) }
    ]);
}
