"""Type stubs for geo-toolbox Python bindings."""

from typing import Any, Optional, TypedDict


class CrsDef:
    """CRS definition returned by CrsEngine.list_all()."""
    epsg: int
    name: str
    proj4: str
    category: str


class CrsEngine:
    """Coordinate Reference System engine with built-in transforms."""
    def __init__(self) -> None: ...
    def list_all(self) -> list[CrsDef]: ...
    def transform(self, from_epsg: int, to_epsg: int, x: float, y: float) -> tuple[float, float]: ...
    def transform_batch(self, from_epsg: int, to_epsg: int, coords: list[float]) -> list[float]: ...


class CarbonEngine:
    """Carbon emission calculation engine (IPCC Tier 1)."""
    def __init__(self) -> None: ...
    def calculate(self, geojson: str | dict, factors_csv: str, year: int) -> str: ...
    def calculate_with_json_factors(self, geojson: str | dict, factors_json: str, year: int) -> str: ...


class MvtEncoder:
    """Mapbox Vector Tile encoder."""
    def __init__(self, extent: int = 4096) -> None: ...
    def add_layer(self, name: str, features: list[dict], tile_x: int, tile_y: int, zoom: int) -> None: ...
    def encode(self) -> bytes: ...


# ── Tile math ──

def latlon_to_tile(lat: float, lon: float, zoom: int) -> tuple[int, int, int]: ...
def tile_to_latlon(x: int, y: int, zoom: int) -> tuple[float, float, float, float]: ...
def tile_url(source: str, x: int, y: int, zoom: int) -> str: ...

# ── Spatial ──

def compute_area_sqm(geojson_geom: str) -> float: ...
def compute_bbox(geojson_geom: str) -> tuple[float, float, float, float]: ...
def compute_centroid(geojson_geom: str) -> tuple[float, float]: ...
def simplify_geometry(geojson_geom: str, epsilon: float) -> str: ...
def convex_hull(geojson_geom: str) -> str: ...

# ── IO ──

def parse_csv_to_json(csv_text: str) -> list[dict[str, str]]: ...
def generate_geojson(features: list[dict]) -> str: ...
def generate_excel(columns: list[str], rows: list[list[Any]], sheet_name: Optional[str] = None) -> bytes: ...
def generate_carbon_report_md(report: dict, aoi_name: str, auditor: str) -> str: ...

# ── Ingest ──

def parse_nmea(sentence: str) -> dict[str, str]: ...
def parse_nmea_batch(sentences: list[str]) -> list[dict[str, str]]: ...
def validate_coord(lat: float, lon: float) -> tuple[bool, str]: ...
def validate_gps_fix(quality: int) -> tuple[bool, str]: ...
def validate_sensor_reading(value: float, sensor_type: str, min_val: float, max_val: float) -> tuple[bool, str]: ...

# ── Geohash ──

def geohash_encode(lat: float, lon: float, precision: int = 8) -> str: ...
def geohash_decode(hash: str) -> tuple[float, float, float, float]: ...
def geohash_neighbors(hash: str) -> list[str]: ...

# ── Version ──

__version__: str
