/// MODFLOW-2005 输入文件生成适配器。
///
/// 生成 .NAM / .DIS / .BAS6 / .LPF / .PCG 等标准输入文件。
/// 纯 Rust，无外部依赖，输出为 String 可直接写入文件。
use serde::{Deserialize, Serialize};
use geo_core::traits::{ModflowGrid, ModflowStressPeriod};

/// 生成 MODFLOW-2005 .NAM 名称文件。
pub fn generate_nam(model_name: &str, units: &[(&str, usize)]) -> String {
    let mut out = format!("{}\n", model_name);
    for (ftype, unit) in units {
        let filename = format!("{}.{}", model_name, ftype.to_lowercase());
        out.push_str(&format!("{:<10} {:>5}  {}\n", ftype, unit, filename));
    }
    out
}

/// 生成 MODFLOW-2005 .DIS 离散化文件。
#[allow(clippy::too_many_arguments)]
pub fn generate_dis(
    nlay: usize,
    nrow: usize,
    ncol: usize,
    delr: f64,
    delc: f64,
    top: f64,
    bot: f64,
    nper: usize,
) -> String {
    use std::fmt::Write;
    let mut out = String::new();
    writeln!(out, "# DIS file generated by geo-adapter-modflow").ok();
    writeln!(out, "{} {} {} {} {} {} {}", nlay, nrow, ncol, 0, 0, 0, nper).ok();
    for _ in 0..nrow {
        writeln!(out, "{}", delr).ok();
    }
    for _ in 0..ncol {
        writeln!(out, "{}", delc).ok();
    }
    writeln!(out, "{}", top).ok();
    writeln!(out, "{}", bot).ok();
    out
}

/// 生成 MODFLOW-2005 .BAS6 基础文件。
pub fn generate_bas6(ibound_val: i32, strt: f64, nrow: usize, ncol: usize) -> String {
    use std::fmt::Write;
    let mut out = String::new();
    writeln!(out, "# BAS6 file").ok();
    writeln!(out, "FREE").ok();
    writeln!(out, "IBOUND").ok();
    for _ in 0..nrow {
        let row: Vec<String> = (0..ncol).map(|_| ibound_val.to_string()).collect();
        writeln!(out, "{}", row.join(" ")).ok();
    }
    writeln!(out, "{}", strt).ok();
    out
}

/// 生成 MODFLOW-2005 .LPF 层属性流文件。
pub fn generate_lpf(hk: f64, vka: f64, ss: f64, sy: f64, nrow: usize, ncol: usize) -> String {
    use std::fmt::Write;
    let mut out = String::new();
    writeln!(out, "# LPF file").ok();
    writeln!(out, "{:<15} {}", "HK", 1).ok();
    writeln!(out, "{:<15} {}", "VKA", 1).ok();
    writeln!(out, "{:<15} {}", "SS", 1).ok();
    writeln!(out, "{:<15} {}", "SY", 1).ok();
    for _ in 0..nrow {
        let row: Vec<String> = (0..ncol).map(|_| hk.to_string()).collect();
        writeln!(out, "{}", row.join(" ")).ok();
    }
    for _ in 0..nrow {
        let row: Vec<String> = (0..ncol).map(|_| vka.to_string()).collect();
        writeln!(out, "{}", row.join(" ")).ok();
    }
    for _ in 0..nrow {
        let row: Vec<String> = (0..ncol).map(|_| ss.to_string()).collect();
        writeln!(out, "{}", row.join(" ")).ok();
    }
    for _ in 0..nrow {
        let row: Vec<String> = (0..ncol).map(|_| sy.to_string()).collect();
        writeln!(out, "{}", row.join(" ")).ok();
    }
    out
}

// ════════════════════════════════════════════════════════════════
// Trait implementation: geo_core::traits::ModflowGenerator
// ════════════════════════════════════════════════════════════════

/// MODFLOW 适配器 — 零成员单元结构体，实现 geo_core::traits::ModflowGenerator
pub struct ModflowAdapter;

impl geo_core::traits::ModflowGenerator for ModflowAdapter {
    fn generate_nam(&self, model_name: &str, units: &[(&str, usize)]) -> String {
        generate_nam(model_name, units)
    }

    fn generate_dis(
        &self,
        nlay: usize,
        nrow: usize,
        ncol: usize,
        delr: f64,
        delc: f64,
        top: f64,
        bot: f64,
        nper: usize,
    ) -> String {
        generate_dis(nlay, nrow, ncol, delr, delc, top, bot, nper)
    }

    fn generate_bas6(&self, ibound_val: i32, strt: f64, nrow: usize, ncol: usize) -> String {
        generate_bas6(ibound_val, strt, nrow, ncol)
    }

    fn generate_lpf(
        &self,
        hk: f64,
        vka: f64,
        ss: f64,
        sy: f64,
        nrow: usize,
        ncol: usize,
    ) -> String {
        generate_lpf(hk, vka, ss, sy, nrow, ncol)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_generate_nam() {
        let nam = generate_nam("test", &[("DIS", 11), ("BAS6", 12)]);
        assert!(nam.contains("DIS"));
        assert!(nam.contains("test.dis"));
    }

    #[test]
    fn test_generate_dis() {
        let dis = generate_dis(1, 10, 10, 100.0, 100.0, 50.0, 0.0, 1);
        assert!(dis.contains("1 10 10"));
        assert!(dis.contains("100"));
    }

    #[test]
    fn test_generate_bas6() {
        let bas = generate_bas6(1, 50.0, 3, 4);
        assert!(bas.contains("IBOUND"));
        assert!(bas.contains("1 1 1 1"));
    }

    #[test]
    fn test_generate_lpf() {
        let lpf = generate_lpf(1e-4, 1e-5, 1e-6, 0.2, 2, 3);
        assert!(lpf.contains("HK"));
        assert!(lpf.contains("0.0001"));
    }
}
